// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/errordeveloper/cue-utils/template/testtypes

package testtypes

#Cluster: {
	metadata: #ClusterMeta @go(Metadata)
	spec:     #ClusterSpec @go(Spec)
}

#ClusterMeta: {
	namespace: string @go(Namespace)
	name:      string @go(Name)
}

#ClusterSpec: {
	location:    string        @go(Location)
	subnetCIDR?: null | string @go(SubnetCIDR,*string)
}
